import type { Metadata } from "next";

import "./globals.css";
import { inter } from "@/config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Prop {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<Prop>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
